name: flutterappe
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  url_launcher: ^5.4.11
  http: ^0.12.1

dependency_overrides:
  url_launcher: '5.4.11'


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/foto.jpg
    - assets/images/distance.jpg
    - assets/images/handwassen.jpg
    - assets/images/masker.jpg
    - assets/images/SS.png
    - assets/images/gloves.jpg
  uses-material-design: true
